/* File Name: careerActionTypes.js                                          *
 * Description: Action Types for careers                                    */

const CareerActionTypes = {
    FETCHING_CAREERS: 'FETCHING_CAREERS',
    FETCH_CAREERS_SUCCESS: 'FETCH_CAREERS_SUCCESS',
    FETCH_CAREERS_ERROR: 'FETCH_CAREERS_ERROR',
    CREATE_CAREER_SUCCESS: 'CREATE_CAREER_SUCCESS',
    CREATE_CAREER_ERROR: 'CREATE_CAREER_ERROR',
    EDIT_CAREER_SUCCESS: 'EDIT_CAREER_SUCCESS',
    EDIT_CAREER_ERROR: 'EDIT_CAREER_ERROR',
    DELETE_CAREER_SUCCESS: 'DELETE_CAREER_SUCCESS',
    DELETE_CAREER_ERROR: 'DELETE_CAREER_ERROR',
    SEND_APPLICATION_SUCCESS: 'SEND_APPLICATION_SUCCESS',
    SEND_APPLICATION_ERROR: 'SEND_APPLICATION_ERROR'
}

export default CareerActionTypes