/* File Name: projectActionTypes.js                                         *
 * Description: Action Types for projects                                   */

const ProjectActionTypes = {
    FETCHING_PROJECTS: 'FETCHING_PROJECTS',
    FETCH_PROJECTS_SUCCESS: 'FETCH_PROJECTS_SUCCESS',
    FETCH_PROJECTS_ERROR: 'FETCH_PROJECTS_ERROR',
    CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
    CREATE_PROJECT_ERROR: 'CREATE_PROJECT_ERROR',
    EDIT_PROJECT_SUCCESS: 'EDIT_PROJECT_SUCCESS',
    EDIT_PROJECT_ERROR: 'EDIT_PROJECT_ERROR',
    DELETE_PROJECT_SUCCESS: 'DELETE_PROJECT_SUCCESS',
    DELETE_PROJECT_ERROR: 'DELETE_PROJECT_ERROR',
    UPDATE_MAIN_PROJECT: 'UPDATE_MAIN_PROJECT',
    UPDATE_PROJECT_IMAGE_INDEX: 'UPDATE_PROJECT_IMAGE_INDEX',
    UPDATE_PROJECTS_TO_DISPLAY: 'UPDATE_PROJECTS_TO_DISPLAY'
}

export default ProjectActionTypes